### ISSUE TITLE
Adding seperate sounds for when holding down a key and releasing.

### ISSUE THREAD

**Issue by karimk123** [hainguyents13/mechvibes#49] opened 2020-12-17 22:48 UTC
This is more of a feature request.
This app is AMAZING but there is just one thing missing: Seperate sounds for pushing down a key and releasing a key,  I feel like this is one of the small things that could make this program a lot more realistic and more pleasant in general.
Please add this feature. Thanks!

**Comment by Chowtown** [comment] 2021-01-23 17:19
Completely agree with this, having a different sound for Key Pressed and Key Released is a huge improvement and would attract so much more people.

**Comment by NotLazy** [comment] 2023-10-20 03:38
dupe of #21

**Closed by NotLazy** 2023-10-20 03:38 UTC
