### ISSUE TITLE
Request to add on Startup but minimized .ie without opening window at startup

### ISSUE THREAD

**Issue by lonewolf1508** [hainguyents13/mechvibes#55] opened 2021-01-03 06:31 UTC
hello Good sir, i'm over the moon how such a small software by you can bring happiness to me and make using a pc so much more fun. Please consider my request to add the functionality so that the software begins at startup but totally minimized to system tray, the rest is top notch stuff!!

**Comment by xyz-Yanys** [comment] 2021-01-13 05:53
I think that's too much for a javascript app

**Comment by max-programming** [comment] 2021-01-16 14:55
> hello Good sir, i'm over the moon how such a small software by you can bring happiness to me and make using a pc so much more fun. Please consider my request to add the functionality so that the software begins at startup but totally minimized to system tray, the rest is top notch stuff!!

There is a functionality of startup launch already 🤔

**Comment by Kthateyo** [comment] 2021-02-06 22:11
Yes, there is option "Enable at Startup", but the issue is, that it starts not minimized. After every boot of the computer the Mechvibes window appears at the centre of screen and then every time we have to close it manually. It's just annoying. It should starts minimized on startup.

Is there any problem of implementing this feature or it's just not implemented yet? 😀

**Comment by shivamkainth** [comment] 2021-04-02 11:16
creating a pull request for this one.

**Closed** 2023-10-20 03:41 UTC
