### ISSUE TITLE
'Enable at startup' should start the app in the system tray

### ISSUE THREAD

**Issue by sbhjt-gr** [hainguyents13/mechvibes#182] opened 2022-06-21 09:03 UTC
'Enable at startup' opens up the whole app on every boot. It becomes quite annoying to close it every time. Instead, it would be nice if it always starts in the system tray on every boot.

**Comment by AspectOfJerry** [comment] 2022-07-03 16:15
Duplicate of #169

**Comment by NotLazy** [comment] 2023-10-20 04:07
#55 #169

**Closed by NotLazy** 2023-10-20 04:07 UTC
