### ISSUE TITLE
Mecvibes does not open in POP OS 22.04 with Nvidia Card

### ISSUE THREAD

**Issue by Endrisserp** [hainguyents13/mechvibes#209] opened 2022-10-23 17:30 UTC
Mechvibes does not open both in .deb and in appimage and in the snap it opens, however, the screen is loading and does not load the sounds in POP OS 22.04 with Nvidia Card.
![image](https://user-images.githubusercontent.com/97167616/197405840-05092f12-09d9-4ba6-a007-930b98060944.png)
![image](https://user-images.githubusercontent.com/97167616/197406622-0b13ec7f-8520-48a1-8e38-63fa84621361.png)

**Comment by NotLazy** [comment] 2023-12-24 15:35
Dupe of #171

**Closed by NotLazy** 2023-12-24 15:35 UTC
