### ISSUE TITLE
There is a delay in the sound after mech vibes is left idle on windows

### ISSUE THREAD

**Issue by omk12** [hainguyents13/mechvibes#229] opened 2023-03-24 08:42 UTC
When u dont type for a while. the program goes to sleep ig. when u type again the sound comes after  1-2 seconds. this keeps happening.  Can someone help me with this?

**Comment by Jacksonmills** [comment] 2023-04-05 03:56
I just noticed a similar issue, seems restarting the app made it better again... I was kinda thinking along with this having some kind of delay or adjustment to the timing of when it triggers would be nice as its a little late for me even when working correctly.

But I definitely noticed this bug as well

**Comment by vivekkpatel** [comment] 2023-06-02 17:58
I am recording programming tutorial with keyboard sounds and there's 1-2 second delay for my keyboard stocks

**Comment by Angel-Ponce** [comment] 2023-08-05 00:36
Same problem

**Comment by NotLazy** [comment] 2023-10-19 04:17
Dupe of #12 and #13

**Closed by NotLazy** 2023-10-19 04:17 UTC
