### ISSUE TITLE
(Suggestion) Output

### ISSUE THREAD

**Issue by ghost** [hainguyents13/mechvibes#47] opened 2020-12-14 22:49 UTC
Since this app tries to change the sound of your key clicks why not add a feature where if you have a speaker the clicks will go through the speaker making the keyboard sound more realistic then If it were to just go through the headset

**Comment by hainguyents13** [comment] 2020-12-15 14:49
> Since this app tries to change the sound of your key clicks why not add a feature where if you have a speaker the clicks will go through the speaker making the keyboard sound more realistic then If it were to just go through the headset

it will output to the speaker if you unplug the headset

**Comment by PaxPaxei** [comment] 2020-12-27 05:28
Thats not the point

**Comment by hainguyents13** [comment] 2020-12-27 05:34
> Thats not the point

maybe I misunderstood your question, can you explain it?

**Comment by unique1o1** [comment] 2021-09-03 07:02
I think what @PaxPaxei is trying to say is that since **mechvibes** is trying to emulate the sound of a mechanical keyboard , it would be nice if **mechvibes** allowed us to use the speaker as the default output instead of using the headphone (when it's connected ).

**Comment by NotLazy** [comment] 2023-10-20 03:37
dupe of #16

**Closed by NotLazy** 2023-10-20 03:37 UTC
