### ISSUE TITLE
Feature Request: Start Minimized

### ISSUE THREAD

**Issue by Obspogon** [hainguyents13/mechvibes#169] opened 2022-04-03 01:41 UTC
The window should start closed on startup and only the tray icon should appear. Great for when enabled at startup.

**Comment by AspectOfJerry** [comment] 2022-07-03 16:22
Very good idea.
Duplicate of #128

**Comment by bAN0NYM0US** [comment] 2023-07-18 00:15
Kind of late to be adding to this but it's very easy to fix this issue. Works with any program.
Just open Start, type in Mechvibes and click on Open File Location on the right panel.
Now press the Windows key and R to open Run and type in shell:startup
Copy the shortcut from the start menu folder and paste it into the startup folder.
Once it's pasted, right click on it in the startup folder and go to Properties.
In the Properties window, should already be on the Shortcut tab, but if it's not, click that.
Then in the drop down box for Run, change that from Normal window to Minimized.
Done, reboot and test.
Mechvibes will start on boot, and it will start minimized so you're not bothered by the window on everyboot.

**Comment by theghostkill** [comment] 2023-11-22 07:47
@bAN0NYM0US Did that but didn't work for me. I also tried switching off the 'Enable at Startup' option from Mechvibes settings, but no luck.

**Comment by NotLazy** [comment] 2024-01-20 16:33
Fixed with #285

**Closed by NotLazy** 2024-01-20 16:33 UTC
