### ISSUE TITLE
Possible Memory Leak, insane ram usage

### ISSUE THREAD

**Issue by prince1107** [hainguyents13/mechvibes#246] opened 2023-10-07 22:25 UTC
Mechvibes takes more than 1gb of ram to run? Potential memory leak?

Device:
MacOS Sonoma, Apple M1 Macbook Air

<img width="1251" alt="Screenshot 2023-10-07 at 17 25 09" src="https://github.com/hainguyents13/mechvibes/assets/64969031/7cfe15e7-11ac-420b-b5e5-d3e2f060c3a1">

@hainguyents13

**Comment by NotLazy** [comment] 2023-10-09 16:38
It's possible this is just the result of this app being made in electron. Electron = Chrome, and we all know chrome is a memory hog. Try just restarting the app.

**Comment by prince1107** [comment] 2023-10-10 22:40
I have tried, but every time it goes back to over 1.3GB+ RAM usage, which is a problem since I code using 2GB+ RAM due to my IDEs on a mac with 8GB ram

**Comment by NotLazy** [comment] 2023-10-19 03:35
I'm going to close this as a dupe of #181 but I want to assure you that me and hainguyents are looking into this.

**Closed by NotLazy** 2023-10-19 03:35 UTC
