### ISSUE TITLE
Wayland Support

### ISSUE THREAD

**Issue by Redoxahmii** [hainguyents13/mechvibes#300] opened 2024-03-04 23:22 UTC
Any application that is running on wayland this application has no sound.
I am an Arch and Gnome and most of the things that i use for typing are now running on Wayland and not having this work is very annoying.

**Comment by NotLazy** [comment] 2024-03-04 23:47
Dupe of #86

**Closed by NotLazy** 2024-03-04 23:47 UTC

**Comment by Redoxahmii** [comment] 2024-03-30 14:39
Welp hopefully the bug is fixed as this is now forcing me to run apps with x11 even for supported wayland applications just to have the sound.
