### ISSUE TITLE
Mechvibes in valorant

### ISSUE THREAD

**Issue by SerialKillah** [hainguyents13/mechvibes#112] opened 2021-07-16 16:29 UTC
Mechvibes works , when i open my valorant it doesn't sound anymore?

**Comment by DznDani** [comment] 2021-08-21 02:48
try running it with admin privileges

**Comment by MessiahHamilton** [comment] 2022-01-10 13:20
How do i run admin privileges on my ubuntu os

**Comment by val8119** [comment] 2022-02-12 18:54
> How do i run admin privileges on my ubuntu os

run it with `sudo <command>`

**Comment by AspectOfJerry** [comment] 2022-07-03 16:28
Duplicate of #110

**Closed** 2023-10-20 04:04 UTC
