### ISSUE TITLE
Delay in first few clicks

### ISSUE THREAD

**Issue by saintramon** [hainguyents13/mechvibes#103] opened 2021-06-22 01:06 UTC
Been experiencing this and it's very frustrating. No worries brother, being a developer is hard. Take your time

**Comment by OGTripleK** [comment] 2021-07-07 08:49
There are already other post I saw, my temp solution for now is I opened Mechvibes and move it to Desktop 2 by Press n hold Windowskey + Tab and create new desktop so it won't go to systemtray so it won't go sleep anytime soon and it will be forgotten in desktop 2.

This is my temporary solution tho, if you have a better solution please don't hesitate to reply. Thanks for reading.

**Comment by AspectOfJerry** [comment] 2022-07-03 16:34
Duplicate of #13

**Closed** 2023-10-19 04:11 UTC
