### ISSUE TITLE
Mac M1 Support

### ISSUE THREAD

**Issue by tappydrive** [hainguyents13/mechvibes#134] opened 2021-10-18 10:06 UTC
Seems to be not working well on M1 Mac. sounds are delayed and are not synchronising well

**Comment by vpat-git** [comment] 2022-01-25 19:46
App does not work at all for me on M1

**Comment by mihai-bica** [comment] 2022-06-08 16:31
Works good on macbook air m1 for me. No bigger delays than on windows 10.

**Comment by arga1234** [comment] 2022-09-28 02:19
App does not work at all for me on M1

**Comment by NotLazy** [comment] 2023-10-19 04:14
The app works for me on M1 Pro, without issues. Ensure you've installed rosetta so you can run x64 apps on arm. As for delayed sounds, thats a duplicate of #13

**Closed by NotLazy** 2023-10-19 04:14 UTC
